### ISSUE TITLE
Error wehn running pip install on Ubuntu 22

### ISSUE THREAD

**Issue by jrequejo** [bgailleton/TVD_Condat2013#3]
Hi Boris, 

  I've succesfully used your implementation in the past, but I am unable to install it on Ubuntu 22. I have installed xtensor and xtensor-python with conda, but to no avail. I keep getting the same error. Any idea? I paste the output below:

Thanks,
Jose

ERROR: Command errored out with exit status 1:
   command: /home/jri/anaconda3/envs/sqwavefit/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-lj27max8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-lj27max8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nrz9fwef
       cwd: /tmp/pip-req-build-lj27max8/
  Complete output (33 lines):
  running bdist_wheel
  running build
  running build_ext
  gcc -pthread -B /home/jri/anaconda3/envs/sqwavefit/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jri/anaconda3/envs/sqwavefit/include/python3.5m -c /tmp/tmpk8dvo_4j.cpp -o tmp/tmpk8dvo_4j.o -std=c++14
  cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/jri/anaconda3/envs/sqwavefit/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jri/anaconda3/envs/sqwavefit/include/python3.5m -c /tmp/tmpbx2g14hy.cpp -o tmp/tmpbx2g14hy.o -fvisibility=hidden
  cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  building 'TVDCondat2013' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/src
  gcc -pthread -B /home/jri/anaconda3/envs/sqwavefit/compiler_compat -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Iinclude -Iinclude -I/home/jri/anaconda3/envs/sqwavefit/lib/python3.5/site-packages/numpy/core/include -I/home/jri/anaconda3/envs/sqwavefit/include -I/home/jri/anaconda3/envs/sqwavefit/Library/include -I/home/jri/anaconda3/envs/sqwavefit/include/python3.5m -c src/main.cpp -o build/temp.linux-x86_64-3.5/src/main.o -DVERSION_INFO="0.0.1" -std=c++14 -fvisibility=hidden
  cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  src/main.cpp: In function ‘xt::pyarray<double> TVD(xt::pyarray<double>, double)’:
  src/main.cpp:169:23: error: ‘adapt’ is not a member of ‘xt’; did you mean ‘xadapt’?
    169 |   auto output_2 = xt::adapt(output);
        |                       ^~~~~
        |                       xadapt
  src/main.cpp: In function ‘xt::pyarray<double> D_TVD_R(xt::pyarray<double>, double)’:
  src/main.cpp:328:19: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
    328 |   for(size_t i=1;i<size;i++)
        |                  ~^~~~~
  src/main.cpp:338:19: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
    338 |   for(size_t i=0;i<size;i++)
        |                  ~^~~~~
  src/main.cpp:350:21: error: ‘adapt’ is not a member of ‘xt’; did you mean ‘xadapt’?
    350 |   auto output = xt::adapt(retrend);
        |                     ^~~~~
        |                     xadapt
  src/main.cpp: At global scope:
  src/main.cpp:356:16: error: expected constructor, destructor, or type conversion before ‘(’ token
    356 | PYBIND11_MODULE(TVDCondat2013, m)
        |                ^
  error: command 'gcc' failed with exit status 1

**Comment by jrequejo** [comment]
Ok. I have managed to make it work on Python 3.10 and Ubuntu 22.

Thanks
